In [3]:
import gdown
gdown.download('https://bit.ly/3736JW1', 'ns_book6.csv', quiet=False)

Downloading...
From: https://bit.ly/3736JW1
To: c:\til\ns_book6.csv
100%|██████████| 55.0M/55.0M [00:04<00:00, 13.7MB/s]

'ns_book6.csv'

In [4]:
import pandas as pd
ns_book6 = pd.read_csv('ns_book6.csv', low_memory=False)
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021.0,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021.0,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021.0,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021.0,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021.0,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

- `describe()` 메서드: 데이터프레임에 대한 기술통계를 자동으로 추출해 주는 메서드  
- `count`: 누락된 값을 제외한 데이터 개수  
- `mean`: 평균  
- `std`: 표준편차  
- `min`: 최솟값
- `max`: 최댓값  
- 0.25, 0.5, 0.75: 데이터를 순서대로 늘어 놓았을 때 25%, 50%, 75% 지점에 놓인 값

In [3]:
ns_book6.describe()

                  번호           발행년도           도서권수           대출건수
count  379976.000000  379976.000000  379976.000000  379976.000000
mean   201726.332847    2008.516306       1.135874      11.504629
std    115836.454596       8.780529       0.483343      19.241926
min         1.000000    1947.000000       0.000000       0.000000
25%    102202.750000    2003.000000       1.000000       2.000000
50%    203179.500000    2009.000000       1.000000       6.000000
75%    301630.250000    2015.000000       1.000000      14.000000
max    401681.000000    2650.000000      40.000000    1765.000000

In [5]:
# 도서권수가 0인 행 제외
ns_book7 = ns_book6[ns_book6['도서권수'] > 0]

- `describe()` 메서드의 `percentiles` 매개변수에 위치를 지정하면 원하는 위치에 있는 값을 볼 수 있음

In [5]:
ns_book7.describe(percentiles=[0.3, 0.6, 0.9])

                  번호           발행년도           도서권수           대출건수
count  376770.000000  376770.000000  376770.000000  376770.000000
mean   202977.476649    2008.460076       1.145540      11.593439
std    115298.245784       8.773148       0.473853      19.279409
min         1.000000    1947.000000       1.000000       0.000000
30%    124649.700000    2004.000000       1.000000       2.000000
50%    204550.500000    2009.000000       1.000000       6.000000
60%    243537.400000    2011.000000       1.000000       8.000000
90%    361341.100000    2018.000000       2.000000      28.000000
max    401681.000000    2650.000000      40.000000    1765.000000

- `describe()` 메서드의 `include` 매개변수에 데이터 타입 지정 가능

In [ ]:
ns_book7.describe(include='object') # top: 가장 많이 등장하는 항목, freq: 가장 많이 등장하는 항목의 빈도수

,도서명,저자,출판사,ISBN,세트 ISBN,부가기호,권,주제분류번호,등록일자
count,376770,376770,376770,376770,55866,308252,61793,359792,376770
unique,336408,248850,21875,350810,14875,17,834,12467,4562
top,승정원일기,세종대왕기념사업회 [편],문학동네,9788937430299,9788937460005,0,1,813.6,1970-01-01
freq,250,303,4410,206,702,158235,13282,14816,28185

- `mean()` 메서드: 평균을 계산하는 메서드  
- `median()` 메서드: 중앙값을 계산하는 메서드  
    - 데이터 개수가 짝수일 때는 가운데 두 값을 평균하여 중앙값을 결정  
- `max()` 메서드: 최댓값을 계산하는 메서드  
- `min()` 메서드: 최솟값을 계산하는 메서드  
- `quantile()` 메서드: 원하는 분위수 값을 계산하는 메서드  
- `var()` 메서드: 분산을 계산하는 메서드  
- `std()` 메서드: 표준편차를 계산하는 메서드  
- `mode()` 메서드: 최빈값을 계산하는 메서드

In [7]:
ns_book7['대출건수'].mean()

11.593438968070707

In [8]:
ns_book7['대출건수'].median()

6.0

In [10]:
ns_book7['대출건수'].max()

1765

In [11]:
ns_book7['대출건수'].quantile(0.25)

2.0

- `quantile()` 메서드의 `interpolation` 매개변수를 지정하면 `quantile`을 계산하는 방식을 지정 가능  
    - `linear`(default): 양쪽 분위수에 비례하여 결정  
    - `midpoint`: 분위수에 상관없이 무조건 두 수 사이의 중앙값 사용  
    - `nearest`: 두 수 중에서 가까운 값을 선택

In [12]:
print(pd.Series([1,2,3,4,5]).quantile(0.9))
print(pd.Series([1,2,3,4,5]).quantile(0.9, interpolation='midpoint'))
print(pd.Series([1,2,3,4,5]).quantile(0.9, interpolation='nearest'))

4.6
4.5
5

In [13]:
ns_book7['대출건수'].var()

371.6956304306922

In [14]:
ns_book7['대출건수'].std()

19.27940949382766

In [15]:
ns_book7['도서명'].mode()

0    승정원일기
Name: 도서명, dtype: object

- 기술통계를 구하는 메서드에서 `numeric_only` 매개변수를 `True`로 지정하면 수치형 열만 연산 가능  
- `True`로 지정하지 않으면 모든 데이터 타입의 열에 대해 수행하기 때문에 시간이 오래 걸림

In [ ]:
ns_book7.mean()

In [6]:
ns_book7.mean(numeric_only=True)

번호      202977.476649
발행년도      2008.460076
도서권수         1.145540
대출건수        11.593439
dtype: float64

- `numpy` 라이브러리를 이용해도 여러 기술통계를 구할 수 있음

In [13]:
import numpy as np

# 평균
print(np.mean(ns_book7['대출건수']))   

# 가중 평균
print(np.average(ns_book7['대출건수'], weights=1/ns_book7['도서권수']))    # weights 매개변수로 가중치 지정

# 중앙값
print(np.median(ns_book7['대출건수']))

# 최댓값
print(np.max(ns_book7['대출건수']))

# 분위수
print(np.quantile(ns_book7['대출건수'], [0.25,0.5,0.75]))
print(np.percentile(ns_book7['대출건수'], [75]))

# 분산
print(ns_book7['대출건수'].var())   # 판다스는 디폴트 자유도가 n-1
print(np.var(ns_book7['대출건수'])) # 넘파이는 자유도를 n으로 계산
print(np.var(ns_book7['대출건수'], ddof=1)) # 자유도를 n으로 계산

# 표준편차
print(np.std(ns_book7['대출건수']))

# 최빈값
values, counts = np.unique(ns_book7['도서명'], return_counts=True)  # 별도의 함수를 제공하지 않으므로 unique()를 이용해 고유값과 등장 횟수를 얻음
max_idx = np.argmax(counts) # argmax()를 이용하여 가장 많은 값의 인덱스를 탐색
print(values[max_idx])

11.593438968070707
10.543612175385386
6.0
1765
[ 2.  6. 14.]
[14.]
371.6956304306922
371.694643898775
371.6956304306922
19.279383908693113
승정원일기